project:
  type: website
  output-dir: docs

website:
  title: "My Workshop"
  navbar:
    type: sidebar      # <-- this enables a sidebar
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Materials
        href: materials.qmd

format:
  html:
    theme: cosmo
    css: styles.css
