project:
  type: website
  output-dir: docs

website:
  title: "My Workshop"
  navbar:
    left:
      - index.qmd
      - about.qmd
      - materials.qmd

format:
  html:
    theme: cosmo
    css: styles.css
