project:
  type: website
  output-dir: docs

website:
  title: "My Workshop"
  sidebar:
  style: floating
  collapse-level: 1
  tools:
    - icon: github
      href: https://github.com/Imago-SDRUK/EMBED2Social-Workshop-2026
  contents:
    - index.qmd
    - Materials.qmd
    - text: Imago
      href: https://imago.ac.uk

format:
  html:
    theme: cosmo
    css: styles.css
