website:
  title: "EMBED2Social Workshop 2026"

  page-footer:
    center: |
      [[Imago]{.green}](https://imago.ac.uk), part of the [[Smart Data Research UK]{.blue}](https://www.sdruk.ukri.org/) family.

  repo-url: https://github.com/Imago-SDRUK/EMBED2Social-Workshop-2026
  repo-branch: main

  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/Imago-SDRUK/EMBED2Social-Workshop-2026
    contents:
      - index.qmd
      - Materials.qmd
      - text: Imago
        href: https://imago.ac.uk